import type { Tale } from '@/types'

export const sampleTales: Tale[] = [
  {
    id: 'tale-momotaro',
    title: 'Project Momotaro',
    description: '桃太郎を題材にTaleSoupの基本機能を検証するプロジェクト',
    status: 'ACTIVE',
    entities: [
      {
        id: 'momotaro',
        name: '桃太郎',
        type: 'CHARACTER',
        role: '主人公',
        personality: '勇敢・正義感が強い・頑固な一面もある',
        tags: ['英雄', '冒険者'],
        alive: true,
      },
      {
        id: 'oni-chief',
        name: '鬼大将',
        type: 'CHARACTER',
        role: '拮抗者',
        personality: '傲慢・かつては桃太郎と仲間だった秘密を持つ',
        tags: ['敵対', '元仲間'],
        alive: true,
      },
      {
        id: 'dog',
        name: '犬',
        type: 'CHARACTER',
        role: '仲間',
        personality: '忠実・戦闘が得意・きびだんごに弱い',
        tags: ['同行者'],
        alive: true,
      },
      {
        id: 'monkey',
        name: '猿',
        type: 'CHARACTER',
        role: '仲間',
        personality: '賢い・策略家・少し臆病',
        tags: ['同行者'],
        alive: true,
      },
      {
        id: 'pheasant',
        name: 'キジ',
        type: 'CHARACTER',
        role: '仲間',
        personality: '俊敏・偵察担当・誇り高い',
        tags: ['同行者'],
        alive: true,
      },
      {
        id: 'onigashima',
        name: '鬼ヶ島',
        type: 'PLACE',
        role: '最終決戦の地',
        personality: '',
        tags: ['場所', '要塞'],
      },
      {
        id: 'village',
        name: '故郷の村',
        type: 'PLACE',
        role: '出発点',
        personality: '',
        tags: ['場所'],
      },
    ],
    relationships: [
      { id: 'r1', fromId: 'momotaro', toId: 'dog',       type: 'ALLY',     label: '仲間' },
      { id: 'r2', fromId: 'momotaro', toId: 'monkey',    type: 'ALLY',     label: '仲間' },
      { id: 'r3', fromId: 'momotaro', toId: 'pheasant',  type: 'ALLY',     label: '仲間' },
      { id: 'r4', fromId: 'momotaro', toId: 'oni-chief', type: 'ENEMY',    label: '対立' },
      { id: 'r5', fromId: 'oni-chief',toId: 'onigashima',type: 'CONTROLS', label: '支配' },
      { id: 'r6', fromId: 'momotaro', toId: 'village',   type: 'BELONGS',  label: '出身' },
    ],
    scenes: [
      {
        id: 'scene-1',
        taleId: 'tale-momotaro',
        title: '第1章：桃から生まれた',
        synopsis: '川で洗濯をしていたおばあさんが大きな桃を拾い、中から桃太郎が生まれる。',
        order: 1,
        entityIds: ['momotaro', 'village'],
        events: [],
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'scene-2',
        taleId: 'tale-momotaro',
        title: '第2章：仲間集め',
        synopsis: '鬼退治に向かう桃太郎が、きびだんごを渡して犬・猿・キジを仲間にする。',
        order: 2,
        entityIds: ['momotaro', 'dog', 'monkey', 'pheasant'],
        events: [],
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'scene-3',
        taleId: 'tale-momotaro',
        title: '第3章：鬼ヶ島決戦',
        synopsis: '桃太郎一行が鬼ヶ島に乗り込み、鬼大将と対決する。',
        order: 3,
        entityIds: ['momotaro', 'dog', 'monkey', 'pheasant', 'oni-chief', 'onigashima'],
        events: [],
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
    ],
    twistPatterns: [],
    choiceRecords: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
]
